name: skroot
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.1.0+2

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  carousel_pro: ^1.0.0
  cached_network_image: ^2.0.0
  dio: ^3.0.8
  flutter_bloc: ^3.2.0
  rxdart:
  shared_preferences: ^0.5.3+4
  flare_flutter: ^2.0.1
  shimmer: ^1.0.1
  carousel_slider: ^1.3.1
  expandable: ^3.0.0+1
  flutter_rating_bar: ^3.0.0
  image_picker: any
#  flutter_datetime_picker: ^1.3.8
  tinycolor: ^1.0.2
  flutter_staggered_animations: ^0.1.2
  url_launcher: ^5.4.5
  flutter_open_whatsapp:
  photo_view: ^0.9.2
  image_downloader:
  awesome_dialog:
  progress_dialog: ^1.2.0
  connectivity: ^0.4.5+1
  flutter_spinkit: ^3.1.0
  fluttertoast:
  pin_entry_text_field: ^0.1.4
  introduction_screen: ^1.0.7
  international_phone_input: ^1.0.4
  flutter_swiper: ^1.1.6
  country_code_picker: ^1.4.0
  flutter_slidable: "^0.5.4"
  pin_code_fields:
  image_cropper: 1.2.1
  flutter_image_compress:





  font_awesome_flutter:


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/localization/
    - assets/animations/
    - assets/images/


  fonts:
    - family: PublicSans
      fonts:
        - asset: fonts/PublicSans-Thin.ttf
          weight: 100
        - asset: fonts/PublicSans-Light.ttf
          weight: 300
        - asset: fonts/PublicSans-Regular.ttf
          weight: 400
        - asset: fonts/PublicSans-Medium.ttf
          weight: 500
        - asset: fonts/PublicSans-SemiBold.ttf
          weight: 600
        - asset: fonts/PublicSans-Bold.ttf
          weight: 700
        - asset: fonts/PublicSans-Black.ttf
          weight: 800
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-Regular.ttf

